version: '3.4'

volumes:
  bds:
    external: true

services:

  bds1:
    container_name: emer

    image: itzg/minecraft-bedrock-server
    environment:
      SERVER_NAME: "EmerLand"
      LEVEL_NAME: "EmerLand"
      # "nice village near spawn"
      # LEVEL_SEED: "720057903"
      MAX_PLAYERS: 20
      EULA: "TRUE"
      GAMEMODE: adventure
      DIFFICULTY: normal
      ALLOW_CHEATS: "true"
      WHITE_LIST: "true"
    ports:
      - 19132:19132/udp
      - 39132:39132
      - 39132:39132/udp
      - 39133:39133
      - 39133:39133/udp
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133
    volumes:
      - bds:/data
    stdin_open: true
    tty: true
    restart: unless-stopped


#  bds2:
#    container_name: flat
#
#    image: itzg/minecraft-bedrock-server
#    environment:
#      SERVER_NAME: "FlatLand"
#      LEVEL_NAME: "FlatLand"
#      MAX_PLAYERS: 20
#      EULA: "TRUE"
#      GAMEMODE: creative
#      DIFFICULTY: normal
#      ALLOW_CHEATS: "true"
#    expose:
#      - 19140/udp
#    ports:
#      - 19140:19132/udp
#      - 39140:39140
#      - 39140:39140/udp
#      - 39141:39141
#      - 39141:39141/udp
#    sysctls:
#      net.ipv4.ip_local_port_range: 39140 39141
#    volumes:
#      - bds:/data
#    stdin_open: true
#    tty: true
#    restart: unless-stopped


